# Generated by Django 4.2.16 on 2026-03-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class e.g. bi-tools', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, choices=[('compact', 'Compact'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('other', 'Other')], max_length=50)),
                ('label', models.CharField(help_text='e.g. "Chip Repair" or leave blank for vehicle type pricing', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_starting_price', models.BooleanField(default=True, help_text='Show as "from $X"')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.service')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
