# Generated by Django 4.2.16 on 2026-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/after/'),
        ),
    ]
